FROM golang:alpine

WORKDIR /finalProject/backend/

COPY . .

ENV DBHOST=${DBHOST}
ENV DBUSER=${DBUSER}
ENV DBPASS=${DBPASS}
ENV DBNAME=${DBNAME}
ENV JWT_KEYS=${JWT_KEYS}
ENV DBSSL=${DBSSL}
ENV CLOUD_NAME=${CLOUD_NAME}
ENV CLOUD_KEY=${CLOUD_KEY}



ENV PORT = ${PORT}

RUN go mod vendor
RUN go build -o start
RUN /finalProject/backend/start migrate -u
RUN /finalProject/backend/start seed

CMD [ "/finalProject/backend/start serve" ]