FROM golang:alpine

WORKDIR /finalProject

COPY . /finalProject/

ENV DBHOST=${DBHOST}
ENV DBUSER=${DBUSER}
ENV DBPASS=${DBPASS}
ENV DBNAME=${DBNAME}
ENV JWT_KEYS=${JWT_KEYS}
ENV DBSSL=${DBSSL}

ENV PORT = ${PORT}

RUN go mod tidy
RUN go build -o start

CMD [ "/finalProject/start serve" ]